# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'VoiceHero' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for VoiceHero
  # pod 'PodsLicenseReader', '~> 0.0.3'
  pod 'PermissionScope', '~> 1.0.2'
  # pod 'BubbleTransition', '~> 1.0.1'
  # pod 'BFPaperButton', '~> 2.0.18'
  # pod 'WMGaugeView', '~> 0.0.3'
  pod 'TuningFork', '~> 0.1.1'

  target 'VoiceHeroTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end
